### ISSUE TITLE
from .async import check_async ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by aldeiaBR** [AtomLinter/linter-pylama#102]
Traceback (most recent call last): File "C:\Users\AlcidesNeto.atom\packages\linter-pylama\bin\pylama.py", line 12, in from pylama.main import shell File "C:\Users\AlcidesNeto.atom\packages\linter-pylama\bin\pylama\main.py", line 10 from .async import check_async ^ SyntaxError: invalid syntax

**Comment by gmist** [comment]
Do you use Python >= 3.7?

**Comment by Nandha95** [comment]
I have this issue as well, and my python version is 3.7.1 .

**Comment by flyspaceage** [comment]
Have same issue, using Python 3.7.1

**Comment by Nandha95** [comment]
Works fine after reverting back to Python 3.6

**Comment by SuperOxigen** [comment]
As of python 3.7, `async` became a *reserved keyword*, more info [here](https://docs.python.org/3/whatsnew/3.7.html).

Issue is the relative import of `bin/pylama/async.py` in  `bin/pylama/main.py`.  The easy fix would be to rename `async.py` to something else and updating the import statement in `main.py`.  Perhaps `async_worker.py`?

**Comment by Mrzhangxd** [comment]
Have same issue, using Python 3.7.1

**Comment by claudiodsf** [comment]
I fixed the problem by installing [pylava](https://github.com/pylava/pylava) and using it as external option, as discussed in #100.

**Comment by kevart** [comment]
Same issue with Python 3.7.3

**Comment by Arcanemagus** [comment]
This issue is caused by the bundled version of `pylama` being quite out of date.

You can either:
* Follow #112 for updates on getting the bundled version of `pylama` to work with Python 3.7+
* Go into the settings and change to using the "External" version of `pylama`, making sure that you have installed it on your system of course

**Comment by bxmoreira** [comment]
> 
> 
> This issue is caused by the bundled version of `pylama` being quite out of date.
> 
> You can either:
> 
>     * Follow #112 for updates on getting the bundled version of `pylama` to work with Python 3.7+
> 
>     * Go into the settings and change to using the "External" version of `pylama`, making sure that you have installed it on your system of course
> 
> 
> I personally use the second option as you aren't tied down to the out of date bundled version.



> 
> 
> This issue is caused by the bundled version of `pylama` being quite out of date.
> 
> You can either:
> 
>     * Follow #112 for updates on getting the bundled version of `pylama` to work with Python 3.7+
> 
>     * Go into the settings and change to using the "External" version of `pylama`, making sure that you have installed it on your system of course
> 
> 
> I personally use the second option as you aren't tied down to the out of date bundled version.

Second option is why better! thanks @Arcanemagus 

Folks before changing pylama settings to "External". Go to cmd and pip install pylama. 

Ciao!

**Comment by lcoi** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/87138289/128862221-c36c07a8-f395-4596-a8ba-a1765a2b042f.png)
it works
