### ISSUE TITLE
Support python3 as interpreter for internal pylama

### ISSUE THREAD

**Issue by mfonville** [AtomLinter/linter-pylama#117]
With python2 EOL and distro's not packaging python2 anymore (or deprecating it) and atom also finally dropping python2 as a requirement (today with 1.47.0) and python3 taking its place as default. linter-pylama fails if `python` is not installed, and if it does not refer to `python2`. Because if it points to `python3` instead it gives the error:
```
Traceback (most recent call last): File "/home/xxx/.atom/packages/linter-pylama/bin/pylama.py", line 12, in from pylama.main import shell File "/home/xxx/.atom/packages/linter-pylama/bin/pylama/main.py", line 10 from .async import check_async ^ SyntaxError: invalid syntax
```
Could linter-pylama please support having python3 as interpreter for the internal pylama? either for `python` or with `python3`

**Comment by mfonville** [comment]
(which seems to at least merge PR https://github.com/AtomLinter/linter-pylama/pull/112)
