### ISSUE TITLE
Uncaught ReferenceError: command is not defined

### ISSUE THREAD

**Issue by AdamLeBlanc** [AtomLinter/linter-pylama#13]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-pylama](https://github.com/AtomLinter/linter-pylama) package, v0.1.5

### Stack Trace

Uncaught ReferenceError: command is not defined

```
At /Users/Adam/.atom/packages/linter-pylama/lib/linter-pylama.coffee:192

ReferenceError: command is not defined
    at /Users/Adam/.atom/packages/linter-pylama/lib/linter-pylama.coffee:192:52
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at BufferedProcess.module.exports.BufferedProcess.handleError (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:251:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:193:26
    at process._tickCallback (node.js:357:13)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter-pylama": {
    "usePylint": true,
    "executablePath": "/Library/Python/2.7/site-packages/pylama"
  }
}
```

### Installed Packages

```coffee
# User
language-docker, v1.1.3
linter, v1.4.3
linter-pylama, v0.1.5
pigments, v0.12.0

# Dev
No dev packages
```

**Comment by cemsbr** [comment]
```
ReferenceError: command is not defined
  at /home/cadu/.atom/packages/linter-pylama/lib/linter-pylama.coffee:192:52
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at BufferedProcess.module.exports.BufferedProcess.handleError (/usr/share/atom/resources/app.asar/src/buffered-process.js:251:20)
  at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:240:24)
  at emitOne (events.js:77:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
  at onErrorNT (internal/child_process.js:344:16)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)
```

**Comment by cemsbr** [comment]
@AdamLeBlanc, what is the solution?

**Comment by quasipedia** [comment]
I'm having the same issue, using external pylama with the executable from a custom venv (python3)

**Comment by quasipedia** [comment]
@AdamLeBlanc - Me too would really appreciate to know how you fixed this! :(

**Comment by quasipedia** [comment]
@cemsbr - Don't know if you have found out already, but the error is an error while trying to send out an error message, basically the `command` variable the error message is trying to display is not there, so - if you want to see what the problem really is - you can remove the variable token from the string.

The *real* error is then displayed correctly.  No idea on how @AdamLeBlanc fixed this, though...

**Comment by AdamLeBlanc** [comment]
I just uninstalled everything, reinstalled it and it worked....

**Comment by cemsbr** [comment]
In my case, updating pip packages helped.

**Comment by alexjurkiewicz** [comment]
Yep, `pip install --upgrade pylama` worked here

**Comment by cemsbr** [comment]
Got this error again. I tried to update pylama and it didn't help.

**Comment by LitTomato** [comment]
i found if you try running when you are not on your main script does it
