### ISSUE TITLE
Linter Crash

### ISSUE THREAD

**Issue by chrisgeo** [AtomLinter/linter-pylama#14]
```
/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:74
Hide Stack Trace
TypeError: Cannot read property 'setEncoding' of undefined
  at BufferedProcess.module.exports.BufferedProcess.bufferStream (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:74:13)
  at BufferedProcess.module.exports.BufferedProcess.handleEvents (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:218:14)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:55:12)
  at LinterPylama.lintFile (/Users/chris.george/.atom/packages/linter-pylama/lib/linter-pylama.coffee:183:24)
  at /Users/chris.george/.atom/packages/linter-pylama/lib/linter-pylama.coffee:211:12
  at FSReqWrap.bufWrapper (fs.js:617:5)
```

**Comment by Arcanemagus** [comment]
Are you still seeing this @chrisgeo?

**Comment by chrisgeo** [comment]
I haven't seen it in a while. I'll close out the issue for you. Thank you!

**Comment by Arcanemagus** [comment]
Sorry it took so long for a response!
