### ISSUE TITLE
Failed to activate the linter-pylama package

### ISSUE THREAD

**Issue by joaoportela** [AtomLinter/linter-pylama#16]
1. Open Atom
2. Message shows on screen.

I have recently updated atom and all the plugins to the latest version.

**Atom Version**: 1.0.15
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter-pylama](https://github.com/AtomLinter/linter-pylama) package, v0.2.0

### Stack Trace

Failed to activate the linter-pylama package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.activate (C:\Users\João\.atom\packages\linter-pylama\lib\init.coffee:71:5)
  at Package.module.exports.Package.activateNow (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:245:19)
  at C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:314:19
  at C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:587:20
  at Emitter.module.exports.Emitter.emit (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:772:29)
  at Config.module.exports.Config.setRawValue (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:564:19)
  at Config.module.exports.Config.set (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:356:12)
  at Package.module.exports.Package.enable (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:154:26)
  at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:143:14)
  at HTMLButtonElement.<anonymous> (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\João\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -1:58.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:56.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:56.9.0 python-yapf:formatCode (atom-text-editor.editor)
     -1:54.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:53.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:52.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:52.8.0 python-yapf:checkFormat (atom-text-editor.editor)
     -1:49.6.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:30 core:copy (atom-text-editor#python-yapf.yapfPath.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "live-doc-viewer",
      "python-yapf"
    ]
  },
  "linter-pylama": {
    "executablePath": "c:\\anaconda\\Scripts\\pylama.exe"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.5.3
linter, v1.6.0
linter-pylama, v0.2.0

# Dev
No dev packages
```

**Comment by joaoportela** [comment]
Atom 1.2.0-beta0 fixes this.
