### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-pylama#34]
[Enter steps to reproduce below:]

1. Install `linter-pylama`

**Atom Version**: 1.7.0-beta0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-pylama](https://github.com/AtomLinter/linter-pylama) package, v0.2.8

### Stack Trace

Failed to activate the linter-pylama package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at LinterPylama.initPylama (file:///C:/Users/Landon Abney/.atom/packages/linter-pylama/lib/linter-pylama.coffee:100:25)
    at LinterPylama.initPylama (file:///C:/Users/Landon Abney/.atom/packages/linter-pylama/lib/linter-pylama.coffee:1:1)
    at file:///C:/Users/Landon Abney/.atom/packages/linter-pylama/lib/linter-pylama.coffee:24:11
    at Config.module.exports.Config.observeKeyPath (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\config.js:612:7)
    at Config.module.exports.Config.observe (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\config.js:141:21)
    at new LinterPylama (file:///C:/Users/Landon Abney/.atom/packages/linter-pylama/lib/linter-pylama.coffee:21:36)
    at Object.module.exports.provideLinter (file:///C:/Users/Landon Abney/.atom/packages/linter-pylama/lib/init.coffee:77:21)
    at Package.module.exports.Package.activateServices (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\package.js:349:69)
    at Package.module.exports.Package.activateNow (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\package.js:186:16)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\package.js:92:15)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\package-manager.js:535:21)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:448:29
    at exit (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -0:19.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:19.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:15.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      ".bin",
      "fast-eslint",
      "linter-flow",
      "atom-typescript",
      "markdown-preview-plus",
      "git-control",
      "git-history",
      "linter-gjslint",
      "language-markdown",
      "linter-tidy",
      "language-chef",
      "linter-csslint",
      "linter-bootlint",
      "linter-scss-lint",
      "linter-jscs",
      "svn"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
autocomplete-python, v1.7.2
docblockr, v0.7.3
editorconfig, v1.2.4
file-watcher, v0.4.0
highlight-selected, v0.11.2
language-docker, v1.1.6
language-elixir, v0.12.3
language-haml, v0.23.15
language-ini, v1.14.0
language-powershell, v2.1.0
language-r, v0.4.0
language-reg, v0.0.0
linter, v1.11.3
linter-alex, v2.0.0
linter-coffeelint, v1.1.2
linter-docker, v0.1.2
linter-elixirc, v1.1.5
linter-erb, v1.0.2
linter-eslint, v7.1.1
linter-flake8, v1.13.0
linter-foodcritic, v0.5.2
linter-golinter, v1.2.0
linter-haml, v1.2.0
linter-htmlhint, v1.1.0
linter-javac, v1.8.1
linter-js-yaml, v1.2.5
linter-jshint, v2.0.3
linter-jsonlint, v1.2.1
linter-lintr, v1.0.4
linter-lua, v1.0.1
linter-markdown, v1.5.0
linter-pep8, v1.2.1
linter-perl, v0.7.2
linter-perlcritic, v0.3.3
linter-php, v1.2.0
linter-phpcs, v1.3.1
linter-phpmd, v1.4.1
linter-pylama, v0.2.8
linter-pylint, v1.2.0
linter-rails-best-practices, v0.2.2
linter-reek, v2.1.5
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-stylelint, v2.0.1
linter-tslint, v0.8.3
linter-ui-default, v0.0.2
mapfile-grammar, v0.1.0
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
pigments, v0.24.5
seti-syntax, v0.4.1
seti-ui, v0.9.1
tab-control, v0.6.9
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Ha, thanks! Saw this and filed it so I wouldn't forget about it :stuck_out_tongue:
