### ISSUE TITLE
bad exception in pylama 0.54, python 3, arch linux

### ISSUE THREAD

**Issue by BoteRock** [AtomLinter/linter-pylama#44]
there is a syntax error in pylama version 0.54, the reported traceback is this:

    Traceback (most recent call last): 
    File "~/.atom/packages/linter-pylama/bin/pylama.py", line 8, in from pylama.main import shell 
    File "~/.atom/packages/linter-pylama/bin/pylama/main.py", line 8, in from .config import parse_options, CURDIR, setup_logger 
    File "~/.atom/packages/linter-pylama/bin/pylama/config.py", line 12, in from .lint.extensions import LINTERS 
    File "~/.atom/packages/linter-pylama/bin/pylama/lint/extensions.py", line 19, in from pylama.lint.pylama_pydocstyle import Linter 
    File "~/.atom/packages/linter-pylama/bin/pylama/lint/pylama_pydocstyle.py", line 23 except AssertionError, e: ^ SyntaxError: invalid syntax

the workaround was editing file `~/.atom/packages/linter-pylama/bin/pylama/lint/pylama_pydocstyle.py`, change the `except AssertionError, e:` to `except AssertionError as e:`

**Comment by Arcanemagus** [comment]
Sounds like that embedded version needs updating @gmist, in the meantime you should just install it on your system and use that version @BoteRock.
