### ISSUE TITLE
Doesn't work with virtualenv

### ISSUE THREAD

**Issue by cemsbr** [AtomLinter/linter-pylama#47]
I'm not sure this is because of virtualenv, but I'm getting the following error:

```
Traceback (most recent call last): File "[path omitted]/.atom/packages/linter-pylama/bin/pylama.py", line 8, in from pylama.main import shell File "[path omitted]/.atom/packages/linter-pylama/bin/pylama/main.py", line 8, in from .config import parse_options, CURDIR, setup_logger File "[path omitted]/.atom/packages/linter-pylama/bin/pylama/config.py", line 12, in from .lint.extensions import LINTERS File "[path omitted]/.atom/packages/linter-pylama/bin/pylama/lint/extensions.py", line 49, in LINTERS[entry.name] = entry.load()() File "/usr/lib/python3.5/site-packages/pkg_resources/init.py", line 2229, in load self.require(args, *kwargs) File "/usr/lib/python3.5/site-packages/pkg_resources/init.py", line 2246, in require items = working_set.resolve(reqs, env, installer) File "/usr/lib/python3.5/site-packages/pkg_resources/init.py", line 829, in resolve raise DistributionNotFound(req, requirers) pkg_resources.DistributionNotFound: The 'pylint==1.5.4' distribution was not found and is required by the application
```

```bash
$ pylint --version
No config file found, using default configuration
pylint 1.5.4, 
astroid 1.4.8
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602]
```

**Comment by Arcanemagus** [comment]
It looks like it's falling back to the embedded version, either specify the full path in the executablePath setting, or close all Atom instances and launch it from the virtualenv environment (`atom .` from a terminal with it enabled).

**Comment by cemsbr** [comment]
I launched atom from a virtualenv environment and got ``WARNING:root:Linter pylint not found.``, but I have the same ``pylint --version`` output as above in the same terminal. However, I can see a pyflakes warning, so it means pylama is working without pylint. I don't know how to setup the executablePath. There's no settings for the plugin.

**Comment by cemsbr** [comment]
I could find the settings button in another window and tried to change the Executable Path to the venv pylama. It didn't help even after restarting atom. linter-pylint is working, though.
