### ISSUE TITLE
Uncaught ReferenceError: initPylama is not defined

### ISSUE THREAD

**Issue by fredcamps** [AtomLinter/linter-pylama#58]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [linter-pylama](https://github.com/AtomLinter/linter-pylama) package, v0.8.10

### Stack Trace

Uncaught ReferenceError: initPylama is not defined

```
At /home/codepunk/.atom/packages/linter-pylama/lib/linter-pylama.coffee:33

ReferenceError: initPylama is not defined
    at /home/codepunk/.atom/packages/linter-pylama/lib/linter-pylama.coffee:33:12
    at /usr/share/atom/resources/app.asar/src/config.js:618:16
    at /usr/share/atom/resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:200:28)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:262:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1427:25
```

### Commands

```
     -1:06.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:29.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:28 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:27.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:27.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:24 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:24 settings-view:open (atom-text-editor.editor)
     -0:00.4.0 core:cut (atom-text-editor#linter-pylama.executablePath.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "metrics",
      "go-config",
      "go-get"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter-pylama": {
    "ignoreErrorsAndWarnings": "D203,D212,D213,D404,C0325",
    "lintOnFly": false,
    "useMcCabe": false,
    "usePep257": false,
    "usePep8": false,
    "usePyflakes": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.14 (active)
autocomplete-clang, v0.10.0 (active)
autocomplete-paths, v1.0.5 (active)
autocomplete-python, v1.8.20 (active)
docblockr, v0.9.1 (active)
language-docker, v1.1.7 (active)
linter, v1.11.18 (active)
linter-clang, v3.4.4 (active)
linter-jshint, v3.0.2 (active)
linter-pylama, v0.8.10 (active)
python-tools, v0.6.8 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by fredcamps** [comment]
Sorry Missconfiguration
