### ISSUE TITLE
Error thrown after updating to 0.1.0

### ISSUE THREAD

**Issue by squeaky-pl** [AtomLinter/linter-pylama#8]
``
**Atom Version**: 1.0.0
**System**: "Fedora release
**Thrown From**: [linter-pylama](https://github.com/AtomLinter/linter-pylama) package, v0.1.0

### Stack Trace

Failed to activate the linter-pylama package

```
At ENOENT: no such file or directory, stat 'pylama'

Error: ENOENT: no such file or directory, stat 'pylama'
    at Error (native)
    at fs.statSync (fs.js:846:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
    at LinterPylama.initPylama (/home/squeaky/.atom/packages/linter-pylama/lib/linter-pylama.coffee:124:17)
    at LinterPylama.initPylama (/home/squeaky/.atom/packages/linter-pylama/lib/linter-pylama.coffee:3:61)
    at /home/squeaky/.atom/packages/linter-pylama/lib/linter-pylama.coffee:36:24
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:555:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:135:21)
    at new LinterPylama (/home/squeaky/.atom/packages/linter-pylama/lib/linter-pylama.coffee:33:42)
    at Object.module.exports.provideLinter (/home/squeaky/.atom/packages/linter-pylama/lib/init.coffee:73:23)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "ignoredNames": [
      ".git",
      "*.pyc"
    ],
    "autoHideMenuBar": true
  },
  "linter-pylama": {
    "usePep257": false
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.1.0
linter-pylama, v0.1.0
minimap, v4.10.2
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages

```
```
python --version
Python 2.7.10

which pylama       
/usr/bin/pylama

pylama --version
pylama 6.3.1

ls -al ~/.atom/packages/linter-pylama/bin/
total 16
drwxrwxr-x 3 squeaky squeaky 4096 Jul  7 12:26 .
drwxrwxr-x 5 squeaky squeaky 4096 Jul  7 12:26 ..
drwxrwxr-x 4 squeaky squeaky 4096 Jul  7 12:26 pylama
-rwxrwxr-x 1 squeaky squeaky  500 Jul  7 12:26 pylama.py
```

**Comment by squeaky-pl** [comment]
The problem comes from using external pylama. I think it detects that the binary name is `pylama` (since I have it on the `PATH`) but then you try to call `statSync` on that `pylama` which will try to resolve it relative to current working directory which obviously wont work. You probably want to call `which pylama` to find absolute path to external `pylama` before passing it to `statSync`.
![screenshot from 2015-07-07 12-49-14](https://cloud.githubusercontent.com/assets/754356/8544654/5efd5686-24a7-11e5-85f1-d8f0b7c8437e.png)

**Comment by squeaky-pl** [comment]
The problem can be circumvented by going to settings and switching from external to internal pylama.

**Comment by gmist** [comment]
Thanks you!
